Poli trustpay
ericyupaypal/apmtool pull request #10
Opened 2021-12-03 18:32 UTC by jscheinhorn

Adding two new APMs enabled for autocapture.
Adding stage option for development.
Poli and Trustpay will be enabled for Sandbox and Live after moratorium.

2021-12-04 04:08 UTC, ericyupaypal requested changes

2021-12-04 04:08 UTC, ericyupaypal commented on lib/orders.js
> +	return ['oxxo', 'multibanco', 'boletobancario', 'poli', 'trustpay'].some(val=>val === apm);
Instead of defining this auto capture scheme capability here, can we define it in https://github.com/ericyupaypal/apmtool/blob/master/config/paymentObjects.json? It would be easier to maintain  all of the scheme capabilities in that single file instead of in multiple places.

Adding an additional field to the scheme attributes like so:
`   "poli": {
      "required": ["name","country_code"],
      "schema": {
         "name": "",
         "country_code": ""
      },
     "autoCapture": true
   },`

2021-12-07 00:02 UTC, jscheinhorn commented on lib/orders.js
> +	return ['oxxo', 'multibanco', 'boletobancario', 'poli', 'trustpay'].some(val=>val === apm);
@ericyupaypal added "autoCapture" to each apm

2021-12-07 05:25 UTC, ericyupaypal approved these changes
Approved

2021-12-09 18:53 UTC, merged