feat: add default live testing credentials for boleto, oxxo, and poli
ericyupaypal/apmtool pull request #15
Opened 2022-03-24 16:55 UTC by jscheinhorn

Requested by testing team to use whitelisted and AUS credentials (Poli). 
PP_LIVE_CLIENT_ID_OXXO
PP_LIVE_CLIENT_SECRET_OXXO
PP_LIVE_CLIENT_ID_BOLETO
PP_LIVE_CLIENT_SECRET_BOLETO
PP_LIVE_CLIENT_ID_POLI
PP_LIVE_CLIENT_SECRET_POLI

2022-03-24 18:44 UTC, ericyupaypal requested changes

2022-03-24 18:44 UTC, ericyupaypal commented on lib/orders.js
>  function determineClientId(args) {
If you are adding `scheme` to the args of the function, can you also add it to the comments above?

2022-03-24 18:44 UTC, ericyupaypal commented on lib/orders.js
> +						clientId: process.env[`PP_${environment}_CLIENT_ID_OXXO`],
If these values are missing from the .env file, how does this error out? If the values are missing, can we have them default back to the primary client id (`PP_LIVE_CLIENT_ID_PRIMARY) and secret (`PP_LIVE_CLIENT_SECRET_PRIMARY`) from the .env file?

2022-03-24 20:13 UTC, jscheinhorn commented on lib/orders.js
>  function determineClientId(args) {
added

2022-03-24 20:13 UTC, jscheinhorn commented on lib/orders.js
> +						clientId: process.env[`PP_${environment}_CLIENT_ID_OXXO`],
added default for case of missing env variables

2022-03-24 21:15 UTC, ericyupaypal requested changes
Can we enable the scheme client id and secret override for all schemes? If they don't exist in the env file, it would just use the defaults.

2022-03-24 21:15 UTC, ericyupaypal commented on lib/orders.js
> -	    } else {
For the different schemes, is there any scheme specific logic here other than getting the scheme specific variable from the config file? Can we get rid of the switch statement and allow any scheme client id to be overridden by the config file?

```suggestion
}  else  {
   clientId = process.env[`PP_${environment}_CLIENT_ID_${scheme.toUpperCase()}`] || process.env[`PP_${environment}_CLIENT_ID_${webHookClientTag}`];
   clientSecret = process.env[`PP_${environment}_CLIENT_SECRET_${scheme.toUpperCase()}`] || process.env[`PP_${environment}_CLIENT_SECRET_${webHookClientTag}`];
   resolve({ clientId, clientSecret });
}
```
If the scheme specific variable doesn't exist, it will just default to the environment default for primary or webhook.

This change would mean that any env override would need to match the spelling of the scheme though. So `PP_LIVE_CLIENT_ID_BOLETO` would need to change to `PP_LIVE_CLIENT_ID_BOLETOBANCARIO`

2022-03-24 23:39 UTC, jscheinhorn commented on lib/orders.js
> -	    } else {
Apply this for Live environment only?

2022-03-25 00:01 UTC, jscheinhorn commented on lib/orders.js
> -	    } else {
changed to apply for all apms and environments

2022-03-25 17:59 UTC, ericyupaypal approved these changes

2022-03-25 17:59 UTC, merged